### ISSUE TITLE
lets migrate to the new 3.x of fabric8-maven-plugin

### ISSUE THREAD

**Issue by jstrachan** [fabric8-quickstarts/swarm-camel#5]
the fix is in this branch: 
https://github.com/jstrachan/swarm-camel/blob/f-m-p-3/pom.xml#L154-L171

but it requires this issue to be resolved so that minimal configuration is required in this quickstart
https://github.com/fabric8io/fabric8-maven-plugin/issues/143

**Comment by davsclaus** [comment]
done
